### ISSUE TITLE
Kernel errors when trying to run CLSMImage

### ISSUE THREAD

**Issue by jalexs82** [Fluorescence-Tools/tttrlib#22]
I installed tttrlib using the Anaconda prebuilt binary method (Windows 10, Python 3.7.7). I am working with .ptu files both produced from an SP8 and from custom Picoquant hardware, so the `reading_routine` is either "default" or "SP8". I am able to create the tttrlib object, which successfully pulls all the data from the .ptu file (event_type, routing_channel, macro_time, micro_time). I then try to create the CLSMImage object as follows:

```
ptu_reading_parameter = {
    "marker_frame_start": [4],
    "marker_line_start": 1,
    "marker_line_stop": 2,
    "marker_event_type": 1,
    "n_pixel_per_line": 512,
    "reading_routine": 'SP8',
    "tttr_data": data,
    }
clsm_image = tttrlib.CLSMImage(**ptu_reading_parameter)
```

Whenever I attempt this, the kernel restarts with a warning ("[SpyderKernelApp] WARNING | No such comm: 585492d2d6ad11eaaa82878b32ad1518"). The same issue happens if I do this using Jupyter, so it doesn't seem to be specifically a Spyder issue.

I am able to get a CLSMImage object if I try to assign it as follows:

```
data = tttrlib.TTTR(filename, 'PTU')
clsm_image = tttrlib.CLSMImage(tttr_data = data, reading_routine = 'SP8')

```
However, doing so pops up a warning ("WARNING: No TTTR data or frame marker provided"). Also, calling methods from that CLSMImage object either returns nothing (`clsm_image.get_frames()` returns an empty tuple), or returns a "ValueError: array is too big; `arr.size * arr.dtype.itemsize` is larger than the maximum possible size." error for other methods (`.get_fluorescence_decay_image(data, 256)` or `.get_intensity_image()`).

At first I thought it was just that these files are too big and I run out of memory. However, the error persists even if I'm using small .ptu files (5MB). I'm working on a laptop, but it has a decent amount of memory (16GB) and I've been able to work with much larger arrays than what these could possibly be creating. So, I'm at a loss as to what could be the underlying problem. I've tried searching all these errors, but I couldn't find anything useful.

Is there anything that you can see that I'm missing or doing wrong here?

**Comment by tpeulen** [comment]
It is possible that either

1. the frame marker are not correct (there is no real standard).
2. or there is sth wrong with the version you are using

This cannot be a memory issue as on my 8GB machine I can work with 500MB files. 

For development/testing I only had/have a very limited number of test files. You can post a link to file that I can use to fix this issue here. Alternatively you can send me a file/link to my email address (thomas-otavio.peulen@ucsf.edu). In either case I will fix this issue over the weekend.

**Comment by jalexs82** [comment]
Thank you. Sent an email with the link.

**Comment by tpeulen** [comment]
You should be able to open you file(s) with the Windows tttrlib build in the conda channel (minimum required version 0.0.18)
```
conda install -c tpeulen/label/nightly tttrlib
```
as follows 

```python
import tttrlib
import pylab as p

ptu_file = "AF555-WGA-1.ptu"
data = tttrlib.TTTR(ptu_file, 'PTU')
reading_parameter = {
    "marker_frame_start": [4],
    "marker_line_start": 1,
    "marker_line_stop": 2,
    "marker_event_type": 15,
    "reading_routine": 'SP8',
	"skip_before_first_frame_marker": True
}

clsm = tttrlib.CLSMImage(data, **reading_parameter)
clsm.fill_pixels(channels=[1], tttr_data=data)
print(clsm.intensity.sum())
p.imshow(clsm.intensity.sum(axis=0))
p.show()
```

I hope that helps. Thanks a lot for providing a file. This helps to improve the library.
