### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by JJPPeters** [Fluorescence-Tools/tttrlib#27]
Currently there are 3 different places that describe at least 3 different licenses for this repository.

1. BSD 3-Clause License  - from the file COPYING (and also in github)
2. MPL 2.0 License - described in README.md
3. MIT License - described here: https://tttrlib.readthedocs.io/en/latest/

Which license is the code under?

**Comment by tpeulen** [comment]
Sorry for the late reply. I was working on an update. The license in inconsistencies should be resolved.
The repository is under the "BSD 3-clause license".
