### ISSUE TITLE
Extraction of Histogram traces does not work

### ISSUE THREAD

**Issue by khemmen** [Fluorescence-Tools/tttrlib#6]
import pylab as p
import numpy as np

import tttrlib

data = tttrlib.TTTR("E:\\Users\Hemmen\A488_1.ptu", '0')
mt = data.get_macro_time()

green_indeces = data.get_selection_by_channel(np.array([0, 2]))
red_indeces = data.get_selection_by_channel(np.array([1, 3]))

fig, ax = p.subplots(2, 1, sharex=True, sharey=False)

p.setp(ax[0].get_xticklabels(), visible=False)
ax[0].plot(tttrlib.histogram_trace(mt[green_indeces], 30000), 'g')

ax[1].plot(tttrlib.histogram_trace(mt[red_indeces], 30000), 'r')
ax[1].invert_yaxis()

p.subplots_adjust(left=None, bottom=None, right=None, top=None, wspace=None, hspace=0)

p.show()

executing the script gives the following error:
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-7-bda15744171c> in <module>
     13 
     14 p.setp(ax[0].get_xticklabels(), visible=False)
---> 15 ax[0].plot(tttrlib.histogram_trace(mt[green_indeces], 30000), 'g')
     16 
     17 ax[1].plot(tttrlib.histogram_trace(mt[red_indeces], 30000), 'r')

AttributeError: module 'tttrlib' has no attribute 'histogram_trace'

**Comment by tpeulen** [comment]
I cannot reproduce this error. Very likely you have a relatively old version of `tttrlib` installed. I recommend to install `tttrlib` in its own conda environment.

You can create a new conda environemnt in your command line 

```bash
conda config --add channels conda-forge tpeulen
conda create --name tttrlib
conda install matplotlib numba numpy scipy tttrlib
```

Next time you want to use `tttrlib`simply activate your environment:
```
conda activate tttrlib
```

In case you are using juypter you can follow the instructions on
[stackoverflow](https://stackoverflow.com/questions/37085665/in-which-conda-environment-is-jupyter-executing/39070588) to make sure that jupyter is using your `tttrlib`environment.

**Comment by tpeulen** [comment]
Ok, I just double checked. The version in the anaconda channel was actually pretty old. I just uploaded an new build that supports the requested feature.

**Comment by tpeulen** [comment]
Make sure that you install the version 0.0.8 with python 3.7.
